<#
Develop a simple Django app that displays an unordered list of fruits and ordered list of
selected students for an event.
#>

mkdir second

Set-Location second

python -m venv env

Set-ExecutionPolicy RemoteSigned -Scope CurrentUser

.\env\Scripts\activate

pip install django

Set-Location .\env

django-admin startproject two

Set-Location .\two 

python manage.py startapp fruitlist

@"
"""
Django settings for two project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wtb$hpt3nhh5k2&#u)_17z(kaj7n5c$e46av(obh!*o!3nk8v&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fruitlist'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'two.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'two.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"@ | Set-Content .\two\settings.py

@"
from django.shortcuts import render

def home(request):
    fruits = ["apple" , "banana", "kiwi" , "Avacado", "Mango"]
    students = ["John", "Jane", "Mike" , "Sara" , "ram"]

    context = {
        'fruits':fruits,
        'students':students
    }

    return render(request , 'home.html', context)
"@ | Set-Content .\fruitlist\views.py

mkdir .\fruitlist\templates

@"
<html>
    <head>
        <title>Students and Fruits</title>
    </head>
    <body>
        <div>
            <h1>Fruits</h1>
            <ul>
                {% for fruit in fruits %}
                <li> {{fruit}} </li>
                {% endfor %}
            <ul>
        </div>
        <div>    
            <h1> Students </h1>
            <ol>
                {% for student in students %}
                <li> {{student}} </li>
                {% endfor %}
            </ol>
        </div>
    <body>
<html>
"@ | Set-Content .\fruitlist\templates\home.html

@"
from django.contrib import admin
from django.urls import path
from fruitlist import views

urlpatterns = [
    path("home/", views.home ),
    path('admin/', admin.site.urls),
]
"@ | Set-Content .\two\urls.py 

python manage.py runserver